# This is an example of the docs-pr.yml workflow available from the recrwplay org
name: "Verify Branch"

on:
  push:
    branches:
    - dev
  # schedule:
    # - cron:  '00 16 * * *'

jobs:

  docs-build:
    name: Generate HTML
    uses: neo4j/docs-tools/.github/workflows/reusable-docs-build.yml@dev
    with:
      retain-artifacts: 14
      deploy-id: 0
      package-script: 'publish-verify'
      cli-options: '--extension ./.docs-tools/extensions/antora/aliases-redirects'

  docs-verify:
    name: Verify HTML
    needs: docs-build
    uses: neo4j/docs-tools/.github/workflows/reusable-docs-verify.yml@dev

  docs-links:
    name: Check links
    needs: docs-build
    uses: neo4j/docs-tools/.github/workflows/reusable-docs-links.yml@dev

  docs-lint:
    name: Lint docs
    uses: neo4j/docs-tools/.github/workflows/reusable-docs-vale.yml@dev