name: Verify HTML

permissions:
  contents: none
  pull-requests: none

on:
  workflow_call:
    inputs:
      failOnErrors:
        description: 'Fail on log errors (boolean)'
        type: boolean
        default: true
      failOnWarnings:
        description: 'Fail on log warnings (boolean)'
        type: boolean
        default: false
        
jobs:
  log-report:
    runs-on: ubuntu-latest

    steps:

    - name: Download Antora log
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: antora-log

    - name: Analyze Antora log
      id: antora-log-check-test
      uses: neo4j/antora-log-analyzer@c5362639f36edaabe719bfcbed32b7938d834615 # v1
      with:
        fail-on-errors: ${{ inputs.failOnErrors }}
        fail-on-warnings: ${{ inputs.failOnWarnings }}
