name: Generate HTML

on:
  workflow_call:
    inputs:
      build-ref:
        description: 'The git ref (branch or tag) to checkout'
        required: false
        type: string
        default: ''
      fetch-depth:
        description: 'The git fetch depth: 1 to fetch just the ref (branch or tag), 0 for full history'
        required: false
        type: number
        default: 1
      docs-dir:
        description: 'The working directory to run jobs in'
        required: false
        type: string
        default: '.'
      node-version:
        description: 'The Node.js version to use'
        required: false
        type: string
        default: '20'
      package-script:
        description: 'The name of the script to run in package.json '
        type: string
        default: 'verify:preview'
      antora-attributes:
        description: 'Antora attributes to pass to the build script'
        required: false
        type: string
        default: ''
      antora-ui-bundle-url:
        description: 'Antora UI bundle URL'
        required: false
        type: string
        default: 'https://static-content.neo4j.com/build/ui-bundle-latest.zip'
      antora-cli-options:
        description: 'Antora CLI options to pass to the build script'
        required: false
        type: string
        default: ''
      antora-extensions:
        description: 'Antora extensions to pass to the build script'
        required: false
        type: string
        default: '
          @neo4j-antora/aliases-redirects
          @neo4j-antora/antora-modify-sitemaps
          @neo4j-antora/antora-page-list
          @neo4j-antora/antora-unlisted-pages
          @neo4j-antora/roles-labels
          @neo4j-antora/selector-labels
          @neo4j-antora/table-footnotes
          @neo4j-antora/xref-hash-validator
          '
      antora-extensions-exclude:
        description: 'Antora extensions to NOT pass to the build script'
        required: false
        type: string
        default: 'na'
      deploy-id:
        description: 'The Deploy ID or PR number if workflow called by a PR'
        required: false
        type: number
        default: 0
      retain-artifacts:
        description: 'The number of days to retain artifacts'
        type: number
        default: 28
      page-list:
        description: 'Upload page list artifact'
        type: boolean
        default: true
      site-dir:
        description: '(Deprecated) The root directory of the generated HTML inside the build directory, defined in an Antora playbook.'
        type: string
        default: ''
        required: false

    outputs:
        pages-listed:
          description: "Page list artifact was uploaded"
          value: ${{ jobs.build-docs.outputs.pages-listed }}

jobs:

  build-docs:
    runs-on: ubuntu-latest
    outputs:
      pages-listed: ${{ steps.page-list-artifact.outcome }}

    env:
      PACKAGE_SCRIPT: ${{ inputs.package-script }}
      NODE_VERSION: ${{ inputs.node-version }}
      DEPLOY_ID: ${{ inputs.deploy-id }}
      BUILD_REF: ${{ inputs.build-ref || '' }}
      FETCH_DEPTH: ${{ inputs.fetch-depth }}
      DOCS_DIR: ${{ inputs.docs-dir }}
      SITE_DIR: ${{ inputs.site-dir }}
      ANTORA_CLI_OPTIONS: ${{ inputs.antora-cli-options }}
      ANTORA_UI_BUNDLE_URL: ${{ inputs.antora-ui-bundle-url }}
      ANTORA_ATTRIBUTES: ${{ inputs.antora-attributes }}
      ANTORA_EXTENSIONS: ${{ inputs.antora-extensions }}
      ANTORA_EXTENSIONS_EXCLUDE: ${{ inputs.antora-extensions-exclude }}
      ANTORA_AI_SEARCH_LINK: "${{ inputs.package-script == 'verify:publish' && '--attribute page-chatbot=https://neo4j.com/docs/assets/chatbot' || '' }}"

    steps:

    # Checkout the whole repo
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      if: ${{ env.DOCS_DIR == '.' }}
      with:
        ref: ${{ env.BUILD_REF }}
        fetch-depth: ${{ env.FETCH_DEPTH }}

    # Checkout the docs dir
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      if: ${{ env.DOCS_DIR != '.' }}
      with:
        ref: ${{ env.BUILD_REF }}
        fetch-depth: ${{ env.FETCH_DEPTH }}
        sparse-checkout: ${{ env.DOCS_DIR }}
        sparse-checkout-cone-mode: false

    - name: Remove excluded extensions
      run: |
        for extension in $ANTORA_EXTENSIONS; do
          if [[ $ANTORA_EXTENSIONS_EXCLUDE =~ "$extension" ]]; then
            continue
          fi
          filtered_extensions=" ${extension} ${filtered_extensions}"
        done
        echo "ANTORA_FILTERED_EXTENSIONS=${filtered_extensions}" >> $GITHUB_ENV

    - name: Create list of extensions for the Antora CLI
      run: |
        for extension in $ANTORA_FILTERED_EXTENSIONS; do
          antora_cli_extensions="--extension ${extension} ${antora_cli_extensions}"
        done
        echo "ANTORA_CLI_EXTENSIONS=${antora_cli_extensions}" >> $GITHUB_ENV

    - name: Use Node.js version ${{ env.NODE_VERSION }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install required extensions - except any excluded by the workflow input
      working-directory: ${{ env.DOCS_DIR }}
      run: |
        # Install dependencies
        npm install --omit=dev

        # Install Antora extensions
        npm install $ANTORA_FILTERED_EXTENSIONS
        
        # Ensure a correct version of sitemaps extension
        npm install @neo4j-antora/antora-modify-sitemaps@0.7.2
        
        # Update extensions
        npm update
        
        # Ensure correct version of Antora
        npm uninstall @antora/cli @antora/site-generator-default
        npm install antora@3.1.14
        
        # List installed packages
        npm list

    - name: Run package script
      working-directory: ${{ env.DOCS_DIR }}
      run: npm run $PACKAGE_SCRIPT -- --ui-bundle-url=$ANTORA_UI_BUNDLE_URL $ANTORA_CLI_OPTIONS $ANTORA_CLI_EXTENSIONS $ANTORA_ATTRIBUTES $ANTORA_AI_SEARCH_LINK

    - name: Get the dir that contains the HTML
      working-directory: ${{ env.DOCS_DIR }}
      id: get-site-dir
      run: |
        shopt -s globstar
        root=$(ls -R build/**/sitemap.xml | head -1 | sed -r 's/build\/([^\/]*).*/\1/')
        echo "site-dir=$root" >> $GITHUB_OUTPUT

    - name: site-dir deprecation notice
      if: ${{ env.SITE_DIR != '' }}
      run: echo "::notice::The site-dir input is deprecated. The value is automatically determined from the build output. You can remove this input from your workflow."

    - name: Save event-id
      working-directory: ${{ env.DOCS_DIR }}
      run: echo $DEPLOY_ID > ./build/${{ steps.get-site-dir.outputs.site-dir }}/deployid

    # we could set include-hidden-files to true to include the .etc and .meta dirs
    - name: Upload HTML artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: docs
        path: ${{ env.DOCS_DIR }}/build/${{ steps.get-site-dir.outputs.site-dir }}
        include-hidden-files: true
        retention-days: ${{ inputs.retain-artifacts }}          

    - name: Upload Log artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: antora-log
        path: ${{ env.DOCS_DIR }}/build/log
        retention-days: ${{ inputs.retain-artifacts }}

    - name: Upload Page List artifact
      id: page-list-artifact
      if: ${{ inputs.page-list }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: page-list
        path: ${{ env.DOCS_DIR }}/build/${{ steps.get-site-dir.outputs.site-dir }}/.meta/pageList
        if-no-files-found: ignore
        retention-days: ${{ inputs.retain-artifacts }}

    # upload an artifact for the redirects file is the aliases redirects extension is not excluded
    - name: Upload Redirects artifact
      id: redirects-artifact
      if: ${{ !contains(inputs.antora-extensions-exclude, '@neo4j-antora/aliases-redirects') }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: redirects
        path: ${{ env.DOCS_DIR }}/build/${{ steps.get-site-dir.outputs.site-dir }}/.etc/**
        if-no-files-found: ignore
        include-hidden-files: true
        retention-days: ${{ inputs.retain-artifacts }}
