name: Generate HTML

on:
  workflow_call:
    inputs:
      deploy-branch:
        description: 'The branch to deploy'
        required: false
        type: string
        default: 'main'
      fetch-depth:
        description: 'Fetch all commits or the latest'
        required: false
        type: number
        default: 1
      package-script:
        description: 'The name of the script to run in package.json '
        type: string
        default: 'build-verify'
      cli-attributes:
        description: 'Asciidoc attribute values to pass for this build'
        required: false
        type: string
        default: '--attribute page-chatbot="/docs/assets/chatbot"'
      cli-default:
        description: 'Default options (extensions) to pass to the build script'
        required: false
        type: string
        default: '--extension ./.docs-tools/extensions/antora/antora-page-list --extension ./node_modules/@neo4j-antora/aliases-redirects'
      cli-options:
        description: 'Options to pass to the build script'
        required: false
        type: string
        default: '--extension ./.docs-tools/extensions/antora/antora-unlisted-pages'
      site-dir:
        description: 'The built site root directory'
        type: string
        default: 'site'
      deploy-id:
        description: 'The Deploy ID or PR number if workflow called by a PR'
        required: true
        type: number
        default: 0
      retain-artifacts:
        description: 'The number of days to retain artifacts'
        type: number
        default: 7
      pageList:
        description: 'Upload page list artifact'
        type: boolean
        default: true
    outputs:
        pages-listed:
          description: "Page list artifact was uploaded"
          value: ${{ jobs.build-docs.outputs.pages-listed }}
  workflow_dispatch:
    inputs:
      deploy-branch:
        description: 'The branch to deploy'
        type: string
        default: '${{ github.ref_name}}'
      fetch-depth:
        description: 'Fetch all commits or the latest'
        type: number
        default: 1
      package-script:
        description: 'The name of the script to run in package.json '
        required: true
        type: string
        default: 'build-verify'
      cli-attributes:
        description: 'Asciidoc attribute values to pass for this build'
        required: false
        type: string
        default: '--attribute page-chatbot="/docs/assets/chatbot"'
      cli-default:
        description: 'Default options (extensions) to pass to the build script'
        required: false
        type: string
        default: '--extension ./.docs-tools/extensions/antora/antora-page-list --extension ./node_modules/@neo4j-antora/aliases-redirects'
      cli-options:
        description: 'Options to pass to the build script'
        required: false
        type: string
        default: '--extension ./.docs-tools/extensions/antora/antora-unlisted-pages'
      site-dir:
        description: 'The built site root directory'
        type: string
        default: 'site'
      deploy-id:
        description: 'A deploy ID'
        required: true
        type: number
        default: 0
      retain-artifacts:
        description: 'The number of days to retain artifacts'
        type: number
        default: 7
      pageList:
        description: 'Upload page list artifact'
        required: false
        type: boolean
        default: true


jobs:
  build-docs:
    runs-on: ubuntu-latest
    outputs:
      pages-listed: ${{ steps.page-list-artifact.outcome }}

    env:
      PACKAGE_SCRIPT: ${{ inputs.package-script }}
      DEPLOY_ID: ${{ inputs.deploy-id }}
      CLI_ATTRIBUTES: ${{ inputs.cli-attributes }}
      CLI_DEFAULT: ${{ inputs.cli-default }}
      CLI_OPTIONS: ${{ inputs.cli-options }}
      FETCH_DEPTH: ${{ inputs.fetch-depth }}
      DEPLOY_BRANCH: ${{ inputs.deploy-branch }}

    steps:    
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ env.FETCH_DEPTH }}
        ref: ${{ env.DEPLOY_BRANCH }}

    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: neo4j/docs-tools
        ref: dev
        sparse-checkout: |
          extensions/antora
        path: .docs-tools

    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install --omit=dev

    - name: Run package script
      run: npm run $PACKAGE_SCRIPT -- $CLI_DEFAULT $CLI_OPTIONS $CLI_ATTRIBUTES

    - name: Save event-id
      run: echo $DEPLOY_ID > ./build/deployid

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: build/
        retention-days: ${{ inputs.retain-artifacts }}          

    - name: Upload Log artifact
      uses: actions/upload-artifact@v4
      with:
        name: antora-log
        path: build/log
        retention-days: ${{ inputs.retain-artifacts }}

    - name: Upload Page List artifact
      id: page-list-artifact
      uses: actions/upload-artifact@v4
      with:
        name: page-list
        path: build/${{ inputs.site-dir }}/.meta/pageList
        retention-days: ${{ inputs.retain-artifacts }}
