name: Generate HTML

on:
  workflow_call:
    inputs:
      package-script:
        description: 'The name of the script to run in package.json '
        type: string
        default: 'build-verify'
      cli-options:
        description: 'Options to pass to the build script'
        required: false
        type: string
        default: ''
      deploy-id:
        description: 'The Deploy ID or PR number if workflow called by a PR'
        required: true
        type: number
        default: 0
      retain-artifacts:
        description: 'The number of days to retain artifacts'
        type: number
        default: 7
      pageList:
        description: 'Upload page list artifact'
        type: boolean
        default: true
    outputs:
        pages-listed:
          description: "Page list artifact was uploaded"
          value: ${{ jobs.build-docs.outputs.pages-listed }}
  workflow_dispatch:
    inputs:
      package-script:
        description: 'The name of the script to run in package.json '
        required: true
        type: string
        default: 'build-verify'
      cli-options:
        description: 'Options to pass to the build script'
        required: false
        type: string
        default: ''
      deploy-id:
        description: 'A deploy ID'
        required: true
        type: number
        default: 0
      retain-artifacts:
        description: 'The number of days to retain artifacts'
        type: number
        default: 7
      pageList:
        description: 'Upload page list artifact'
        required: false
        type: boolean
        default: true


jobs:
  build-docs:
    runs-on: ubuntu-latest
    outputs:
      pages-listed: ${{ steps.page-list-artifact.outcome }}

    env:
      PACKAGE_SCRIPT: ${{ inputs.package-script }}
      DEPLOY_ID: ${{ inputs.deploy-id }}
      CLI_DEFAULT: '--extension ./.docs-tools/extensions/antora/antora-page-list --extension ./.docs-tools/extensions/antora/antora-unlisted-pages'
      CLI_OPTIONS: ${{ inputs.cli-options }}

    steps:    
    - uses: actions/checkout@v3

    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: neo4j/docs-tools
        ref: dev
        sparse-checkout: |
          extensions/antora
        path: .docs-tools

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install --omit=dev

    - name: Run package script
      run: npm run $PACKAGE_SCRIPT -- $CLI_DEFAULT $CLI_OPTIONS

    - name: Save event-id
      run: echo $DEPLOY_ID > ./build/deployid

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: build/
        retention-days: ${{ inputs.retain-artifacts }}          

    - name: Upload Log artifact
      uses: actions/upload-artifact@v3
      with:
        name: antora-log
        path: build/log
        retention-days: ${{ inputs.retain-artifacts }}

    - name: Upload Page List artifact
      id: page-list-artifact
      if: ${{ inputs.pageList }}
      uses: actions/upload-artifact@v3
      with:
        name: page-list
        path: build/site/.meta/pageList
        retention-days: ${{ inputs.retain-artifacts }}
