name: Generate HTML

on:
  workflow_call:
    inputs:
      package-script:
        description: 'The name of the script to run in package.json '
        type: string
        default: 'build-verify'
      antora-attributes:
        description: 'Antora attributes to pass to the build script'
        required: false
        type: string
        default: ''
      antora-cli-options:
        description: 'Antora CLI options to pass to the build script'
        required: false
        type: string
        default: '--ui-bundle-url=https://static-content.neo4j.com/build/ui-bundle-latest.zip'
      antora-extensions:
        description: 'Antora extensions to pass to the build script'
        required: false
        type: string
        default: '
          @neo4j-antora/aliases-redirects
          @neo4j-antora/antora-modify-sitemaps
          @neo4j-antora/antora-page-list
          @neo4j-antora/antora-unlisted-pages
          @neo4j-antora/selector-labels
          @neo4j-antora/xref-hash-validator
          '
      site-dir:
        description: 'The built site root directory'
        type: string
        default: 'site'
      deploy-id:
        description: 'The Deploy ID or PR number if workflow called by a PR'
        required: true
        type: number
        default: 0
      retain-artifacts:
        description: 'The number of days to retain artifacts'
        type: number
        default: 28
      pageList:
        description: 'Upload page list artifact'
        type: boolean
        default: true
    outputs:
        pages-listed:
          description: "Page list artifact was uploaded"
          value: ${{ jobs.build-docs.outputs.pages-listed }}
  workflow_dispatch:
    inputs:
      package-script:
        description: 'The name of the script to run in package.json '
        required: true
        type: string
        default: 'build-verify'
      antora-attributes:
        description: 'Antora attributes to pass to the build script'
        required: false
        type: string
        default: ''
      antora-cli-options:
        description: 'Antora CLI options to pass to the build script'
        required: false
        type: string
        default: '--ui-bundle-url=https://static-content.neo4j.com/build/ui-bundle-latest.zip'
      antora-extensions:
        description: 'Antora extensions to pass to the build script'
        required: false
        type: string
        default: '
          @neo4j-antora/aliases-redirects
          @neo4j-antora/antora-modify-sitemaps
          @neo4j-antora/antora-page-list
          @neo4j-antora/antora-unlisted-pages
          @neo4j-antora/selector-labels
          @neo4j-antora/xref-hash-validator
          '
      site-dir:
        description: 'The built site root directory'
        type: string
        default: 'site'
      deploy-id:
        description: 'A deploy ID'
        required: true
        type: number
        default: 0
      retain-artifacts:
        description: 'The number of days to retain artifacts'
        type: number
        default: 7
      pageList:
        description: 'Upload page list artifact'
        required: false
        type: boolean
        default: true


jobs:
  build-docs:
    runs-on: ubuntu-latest
    outputs:
      pages-listed: ${{ steps.page-list-artifact.outcome }}

    env:
      ANTORA_AI_SEARCH_LINK: "${{ inputs.package-script == 'publish-verify' && '--attribute page-chatbot=''https://neo4j.com/docs/assets/chatbot''' || '' }}"
      PACKAGE_SCRIPT: ${{ inputs.package-script }}
      DEPLOY_ID: ${{ inputs.deploy-id }}
      ANTORA_CLI_OPTIONS: ${{ inputs.antora-cli-options }}
      ANTORA_ATTRIBUTES: ${{ inputs.antora-attributes }}
      ANTORA_EXTENSIONS: ${{ inputs.antora-extensions }}

    steps:

    - uses: actions/checkout@v4

    - name: Create list of extensions for the Antora CLI
      run: |
        for extension in $ANTORA_EXTENSIONS; do
          antora_cli_extensions="--extension ${extension} ${antora_cli_extensions}"
        done
        echo "ANTORA_EXTENSIONS_CLI=${antora_cli_extensions}" >> $GITHUB_ENV

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --omit=dev

    - name: Install extensions
      run: npm install $ANTORA_EXTENSIONS

    - name: Update packages
      run: npm update

    - name: Ensure correct version of antora-modify-sitemaps
      run: npm install @neo4j-antora/antora-modify-sitemaps@0.7.1

    - name: List packages
      run: npm list

    - name: Run package script
      run: npm run $PACKAGE_SCRIPT -- $ANTORA_EXTENSIONS_CLI $ANTORA_CLI_OPTIONS $ANTORA_ATTRIBUTES $ANTORA_AI_SEARCH_LINK

    - name: Save event-id
      run: echo $DEPLOY_ID > ./build/deployid

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: build/
        retention-days: ${{ inputs.retain-artifacts }}          

    - name: Upload Log artifact
      uses: actions/upload-artifact@v4
      with:
        name: antora-log
        path: build/log
        retention-days: ${{ inputs.retain-artifacts }}

    - name: Upload Page List artifact
      id: page-list-artifact
      uses: actions/upload-artifact@v4
      with:
        name: page-list
        path: build/${{ inputs.site-dir }}/.meta/pageList
        retention-days: ${{ inputs.retain-artifacts }}
