name: Validate roles.json

permissions:
  contents: read
  pull-requests: none

on:
  pull_request:
    branches:
    - dev
    paths:
    - 'extensions/antora/roles-labels/data/roles.json'


jobs:
  validate-roles-json:
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        sparse-checkout: ./extensions/antora/roles-labels
    
    - name: Use Node.js version 24
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: 24

    - name: Install dependencies
      run: npm install -D
      working-directory: ./extensions/antora/roles-labels

    - name: Validate roles.json
      run: node ./test/validate-json.js
      working-directory: ./extensions/antora/roles-labels